---

availability_zone: melbourne-qh2-uom

#volume
volumes:
  - volume_name: vol1
    vol_size: 60
  - volume_name: vol2
    vol_size: 60
  - volume_name: vol3
    vol_size: 60
  - volume_name: vol4
    vol_size: 60

#Security groups
security_groups:
  - name: ssh_rule
    description: "for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: http_rule
    description: "for http access"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
  - name: db_5984
    description: "for couchdb access"
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0
  - name: 8080_rule
    description: "for tomcat access"
    protocol: tcp
    port_range_min: 8080
    port_range_max: 8080
    remote_ip_prefix: 0.0.0.0/0

security_groups_lists: [ssh_rule, http_rule, db_5984, 8080_rule, internal]

#Instances
instance_names: [webserver, harvester1, harvester2, harvester3]
instance_image: 955a0556-1224-4499-a895-87d54d5cbf32
instance_key: second
instance_flavor: uom.mse.2c9g
